### ISSUE TITLE
[FRQ] Add Persistence

### ISSUE THREAD

**Issue by chriswessels** [graphops/poi-radio#113]
**Problem statement**
Currently, all state for the Radio is kept in-memory. While this is all that is essential for the POI Radio to operate (i.e. detect real-time divergences), persisting state across process restarts results in slightly better quality data/performance, and also unlocks other functionality like smarter notifications (e.g. subgraph divergence state changes, rather than individual POI mismatch notifications) and better dashboards and reporting.

**Expectation proposal**
Move to a persisted state model. Consider a SQL database backend. Consider using https://github.com/launchbadge/sqlx, with SQLite as the (simple) recommended backend for Indexers.

**Alternative considerations**
Alternatively we can keep the Radio stateless, and somehow export the data to an external sink for persistence, however this added complexity likely doesn't make sense. We could also leave the Radio stateless and accept the constraints that come with that.

**Comment by hopeyen** [comment]
What do you think about something like 
- create a serializable data structure that contain all the states
- periodically save cache (to .json since serializable), and/or upon panic use std::panic::catch_unwind
- load cache from json at start of program if file exists

We can get away from using a DB, but the process is similar either way
